openshift/origin-metrics

- metrics.yaml
use the same default values as the deployer/run.sh script
> fix the deployer template

- README.adoc
- docs/deployer_configuration.adoc
Update docs to include the requires hostnames for the Hawkular Metrics and Cassandra certificates.
> Issue_57: Update docs to include the requires hostnames

- heapster-base/0001-Fix-nil-pointer-reference-panic-in-kube_nodes.patch
- heapster-base/Dockerfile
See https://github.com/openshift/origin-metrics/issues/62
> Add patch to get around nil pointer exception

- cassandra/Dockerfile
- cassandra/cassandra-docker.sh
- hack/e2e-tests.sh
- hack/tests/base.sh
- hack/tests/default_cassandra_pod.yaml
- hack/tests/test-base.sh
- hack/tests/test_standalone_docker.sh
In reference to https://github.com/openshift/origin-metrics/issues/58
> Fix typos preventing a standalone Cassandra pod from being startable.

- README.adoc
Just few typos. Fixing them will make reading the doc a little bit easier.
> Fixed some typos in README

- hawkular-metrics/Dockerfile
Fixes API change which causes problems when running on the very latest Origin master
> Update to the latest Hawkular Metrics snapshot

- README.adoc
- deployer/run.sh
Fix documentation on how to use the latest heapster endpoint.
Fix issue with setting the default Cassandra pv size.
> Minor fixes

- deployer/Dockerfile
- hack/build-images.sh
- hack/build-release.sh
- hack/common.sh
- hack/push-release.sh
- hack/release.sh
fix for metrics to https://github.com/openshift/origin/issues/6628
cc @smarterclayton @sosiouxme @mwringe 
Submitting for now until we can agree about our release process
> fix build-images script for origin release process

- hack/tests/ci_test_every_pr.sh
cc @mwringe 
Add support for running tests on merge.  Still could use some refactoring based on @sosiouxme comments
> Add test script to support running tests on merge

- README.adoc
fix readme text for testing and merge
> fix readme text

- docs/hawkular_metrics.adoc
Headers are case insensitive but we shouldn't we use the same form throughout the docs?
> Use Hawkular-Tenant throughout the docs

- cassandra/cassandra-docker-ready.sh
- hawkular-metrics/hawkular-metrics-readiness.py
see https://github.com/openshift/origin-metrics/issues/154
> fix some of the readiness probe error messages.

- hack/e2e-tests.sh
- hack/tests/ci_test_every_pr.sh
- hack/tests/common.sh
Fixes wrong build status reported [here]
(https://ci.openshift.redhat.com/jenkins/job/test-origin-metrics/37/).
> Fixes for ci_test_every_pr.sh

- deployer/run.sh
- deployer/scripts/functions.sh
> Deployer: less-strict (and validated) booleans.

- deployer/run.sh
- deployer/scripts/hawkular.sh
- deployer/templates/hawkular-metrics.yaml
- docs/deployer_configuration.adoc
- docs/hawkular_metrics.adoc
- metrics.yaml
Note: do not merge yet. We still need this PR to be accepted in Hawkular Metrics (https://github.com/hawkular/hawkular-metrics/pull/542) and our docker images update to a version which includes this PR.
PR opened for review in case there are changes which need to be made.
> Add support to enable or disable user write access for metrics.

- hawkular-metrics/Dockerfile
https://trello.com/c/io9V2wh5/205-2-audit-the-metric-images-and-impl-image-guidelines-hawkular-epic-ois-td
> Conform to image guidelines

- deployer/run.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1351730
> Add validation check to the MASTER_URL value.

- hack/README.adoc
Signed-off-by: YuPengZTE <yu.peng36@zte.com.cn>
> The first letter is low-case

- hack/tests/ci_test_every_pr.sh
> Fix issues where command was renamed in CI system.

- README.adoc
- deployer/Dockerfile
- deployer/scripts/hawkular.sh
- deployer/scripts/heapster.sh
- deployer/templates/hawkular-cassandra.yaml
- docs/build.adoc
- docs/cassandra_advance.adoc
- hack/tests/test_default_deploy.sh
- hack/tests/test_heapster.sh
- hawkular-metrics/hawkular-metrics-wrapper.sh
- hawkular-metrics/standalone.xml
> BZ-1391378: update due to oc command changes

- docs/hawkular_metrics.adoc
> Documentation on how to enable Alerts management for a Service Account

- cassandra/0001-Handle-exabyte-sized-filesystems.patch
- cassandra/Dockerfile
- cassandra/logback.xml
- heapster/heapster-wrapper.sh
Cherry pick to move the required commits from master into the release-1.5 branch
> Release 1.5 cherry pick

- hack/release.sh
> Do not delete local image prior to hack/release.sh

- hawkular-metrics/Dockerfile
> Update python client to version 0.5.2

- cassandra/Dockerfile
> Update to Cassandra 3.0.14

- hawkular-metrics/standalone.conf
- hawkular-metrics/standalone.xml
This commit also removes some unused subsystems from standalone.xml in
an attempt to trim the fat.
> WF 11 config changes

- hack/buildconfigs-template.yaml
@jsanda Could you review please?
> Add metrics schema installer image to buildconfig template
