openshift/origin-metrics

README.adoc

Adds a warning to the readme about the importance of setting the persistent volume size.

Persistent Volume Warning

---

heapster/heapster-wrapper.sh

Fix issue where Heapster would require a restart when running on newer versions of OpenShift.
Appears to be caused by a change in how unresolvable hostnames are handled by the OpenShift dns

Fixes restart issue with Heapster on newer versions of OpenShift

---

cassandra/Dockerfile

Seems to only affect older docker versions.

Fix typo which prevents the Cassandra container from being built 

---

README.adoc
deployer/run-hawkular.sh
deployer/run.sh
deployer/templates/heapster.yaml
docs/deployer_configuration.adoc
metrics.yaml

The following patch helps us to better support updating between versions. The `REDEPLOY` option has been modified to no longer delete the pvc and now when it is used we can update all the templates, refresh the certificates (eg in case of expiry) and redeploy all the components. Since the pvc is no longer deleted, all the persisted data will continue to be available.
Since Heapster, Hawkular Metrics and Cassandra are being redeployed during this time, there will be a gap in the metrics while this is occurring.
Ideally we should seamlessly be able to update without a gap in the metrics, but I am unsure how exactly that can be accomplished. There are a lot of components which may be required to be updated between versions and it would get tricky to try and update things as they are all …

Better support updating between versions

---

README.adoc

Adds a diagram so that anyone can quickly ascertain the architecture for origin-metrics just by going to the README.  Reduces a little of the text which is redundant

Add a diagram and consolidate the architecture description

---

hack/build-images.sh

The Heapster base image is meant to just contain the Heapster binary that our normal Heapster image uses. It's currently being tagged with the Heapster version, not the origin-metrics version (see https://github.com/openshift/origin-metrics/blob/master/heapster/Dockerfile#L19).
I don't know if we really want to add this to our main build or not.  We should only be updating this version when a new version of Heapster is released or a patch that we need is merged into Heapster upstream. If we could have gotten away with only using proper Heapster releases, then we could potentially even remove the base image and just download the binary directly.
Any thoughts on this? I would prefer to remove it from the automated build script if possible, how its being done today is wrong in the version …

Remove the heapster base image from the main build.

---

deployer/scripts/functions.sh

Changing the re-deploy to terminate and remove pods immediately by adding --grace-period=0 is more in line with what a REDEPLOY not marked as "refresh" should do. Remove everything that is currently there and not allow the system to leave lingering pods/etc, which currently happens.
This also removes a race condition with NFSv3 PVs which basically fail to get recycled due to the fact that some pods have files open still at the same time as the recycler tries to go in and recycle, but fails due to the fact that there are open files and NFS creates locks, which then break the recycler. Separating the two processes out, eliminates the race condition and should introduce anything "new" just stage the process a bit better than an all in one swoop.

Fix an NFSv3 locking issue

---

deployer/scripts/functions.sh
metrics.yaml

This fixes an issue where the deployer will terminate itself before it finishes being deployed.
Now the deployer will not be removed automatically when the 'redeploy' option is used (which it probably shouldn't have been anyways, since it can hide the fact that it terminated in an error state). But the deployer will still remove old deployer instances when the 'redeploy' option is used (to remove all instances that don't need to be kept around)

Fix issue where the deployer will kill itself before it finishes

---

heapster-base/Dockerfile
heapster-base/golang1.4-compat.patch

Requires a patch to disable a test which uses an api in a more recent golang.

Use the system golang instead of bringing in a newer version.

---

hack/build-images.sh

Fixes an issue where local images cannot be used since the deployer image would always be fetched from docker.io

Remove 'docker.io/' from the docker image when performing a build.

---

hawkular-metrics/Dockerfile

Hawkular should run as numeric user, not named user for OpenShift to also work for SCC with "MustRunAsNonRoot"

Hawkular USER 1000

---

deployer/scripts/validate.sh

In the case of dynamic provisioning of PVs for PVCs, the deployer should wait longer before deciding that something has gone wrong.

deployer validations: wait longer for PVC to be bound

---

deployer/scripts/validate.sh
hack/tests/ci_test_every_pr.sh
metrics.yaml

Updated validations to look at Scheduled events as an antidote to
SchedulingFailed events and give the failures a second chance to be
resolved. This should address the case where a PVC is dynamically bound,
the pod having received a SchedulingFailed in the meantime.
Also, redeploy / refresh no longer attempt to modify the deployer pod
label as this does not seem to be allowed by the server any longer. As a
consequence they also don't attempt to delete previous deployer pods.

deployer: improve validation event handling

---

deployer/scripts/hawkular.sh
deployer/templates/hawkular-metrics.yaml
hawkular-metrics/Dockerfile
hawkular-metrics/client
hawkular-metrics/hawkular-client-initialization.py

This PR adds a pre-initialized Python client to the Hawkular-Metrics pod, for easier debugging and access.
To start it, enter ``client`` in the bash prompt. The client is under variable ``c`` and documentation can be found from [](https://github.com/hawkular/hawkular-client-python )
Resolves #115

Add Hawkular-Metrics client

---

hack/README.adoc
hack/e2e-tests.sh
hack/tests/base.sh
hack/tests/common.sh

- use `getopt(1)` to validate flag names and number of arguments
- centralize parsing so it happens in only one place (for each script)

e2e: improve argument parsing

---

hawkular-metrics/welcome-content/index.html

Updates the redirect to include the url part which makes some browser more happy.
Remove the hard coded version we have in here which shouldn't be there.

Update Hawkular main page for redirect and remove version.

---

cassandra/Dockerfile
cassandra/cassandra-metrics-reporter.yaml

Adds a logging configuration file to the container which, if enabled, can be used to produce Cassandra debugging logs.
To enable this debugging log, you just need to set an env value for the container.
```
- name: JVM_EXTRA_OPTS
value: -Dcassandra.metricsReporterConfigFile=cassandra-metrics-reporter.yaml
```
This is only meant for more debugging cases which get a bit tricky, such as issues with the filesystem not being able to keep up with rights.
Its also possible to add this in manually by creating a confmap, loading the file as a volume, and setting the env var, but this gets a bit more tricky.

Add logging debug file to container.

---

README.adoc

@mwringe , this is a trivial commit on readme, I was first trying to deploy secrets with PEM file that didn't contain any private key and got an error on deployment. I'm not an expert on certificate rfc but I understand that PEM files content is not strictly defined (see http://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file ), so it's worth mentioning that a private key is expected.

Add a note about the certificate PEM file

---

Makefile

In order to interface with the origin-ci-tool that will be
replacing the vagrant-openshfit repository, all actions that
a user (or the CI system) will want to do in this repository
should be supported with a `make` target. This decision to
use `make` as the API between users and the repository was
made with the express purpose of reducing the amount of
complexity that any tool would have to contain.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Added a Makefile with a target to build Docker images

---

README.adoc
deployer/templates/hawkular-metrics.yaml
hack/tests/test_default_deploy.sh
hawkular-metrics/hawkular-metrics-wrapper.sh

Adds docs that the Hawkular service account needs special permissions (required for wildfly/eap jgroups clustering).
Adds check to the Hawkular Metrics image so that it will fail with an error message if the service account does not have the right permissions. This is to help prevent the instances from starting if clustering cannot be enabled.

Check that Hawkular has the required permissions for clustering.

---

deployer/templates/hawkular-cassandra-node-dynamic-pv.yaml
deployer/templates/hawkular-cassandra-node-emptydir.yaml
deployer/templates/hawkular-cassandra-node-pv.yaml

If the Cassandra instance is shut down incorrectly, there is a chance that the commit logs could become corrupted and not be usable. This normally forces an admin to go in and manually delete the commit logs before restarting the server will be possible.
This makes a change that will allow Cassandra to continue if a commit log is corrupted and not salvageable. Allowing the server to continue to boot up.

Set the default Cassandra policy to ignore commit log replay errors

---

deployer/templates/heapster.yaml

The images from repository online only get container metrics. The origin-web-console will display pv metrics in future.  Refer to [https://trello.com/c/6gpwW6uJ/253-pv-monitoring]

Make images built getting summary metrics

---

cassandra/cassandra-docker.sh

The "--truststore_password" parameter had a typo. The old version,
"--trustsotre_password", is still accepted in case it's used somewhere.

Fix typo in cassandra-docker.sh parameter

---

README.adoc
docs/deployer_installation.adoc
hawkular-agent/hawkular-openshift-agent-configmap.yaml
hawkular-agent/hawkular-openshift-agent.yaml

Add in instructions on how to deploy the Hawkular OpenShift Agent.

Deprecate the old deployer way of installing metrics.

---

hawkular-metrics/hawkular-metrics-wrapper.sh

Set the keystore and truststore passwords via an properties file instead of setting directly as properties.

Move the Hawkular passwords to a file.

---

hawkular-openshift-agent/hawkular-openshift-agent-configmap.yaml
hawkular-openshift-agent/hawkular-openshift-agent.yaml

Deploy the agent to the 'default' project so that it works in ovs_multitenant environments.

BZ1421060: deploy the agent to the 'default' project

---

README.adoc

We need to deploy the agent to the 'default' project so that it will continue to be able to monitor all pods even if the ovs_multitenant plugin is running.

Update docs for deploying the agent to the default project.

---

cassandra/0001-Handle-exabyte-sized-filesystems.patch
cassandra/Dockerfile

Creates a separate cassandra-base image which will build Cassandra from source.
Apply patch to allow Cassandra to run on EFS (https://bugzilla.redhat.com/show_bug.cgi?id=1418748)

Create a Cassandra base image so we can more easily apply patches.

---

deployer/templates/heapster.yaml

Changes labelToTenant from pod_namespace (deprecated) to namespace_name. This does not change old behavior:
https://github.com/kubernetes/heapster/blob/b0a73e1c64a2787242368b55efdb542a632ef726/metrics/processors/pod_based_enricher.go
As the same namespace modifier is used in the enriching process, but it fixes the bug in namespace handling:
https://github.com/kubernetes/heapster/blob/96d9dbf9ee20c200bb7703a8dff0b5ea7c1d1ba1/metrics/processors/namespace_aggregator.go#L60
As pod_namespace is not used there, but namespace_name is enriched there.

Change Heapster labelToTenant 

---

deployer/templates/hawkular-cassandra-node-dynamic-pv.yaml

- "alpha" is obsoleted in favour of "beta" in Persistent Volume Claim definition 
more about it in documentation : 
http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html
Signed-off-by: Elvir Kuric <elvirkuric@gmail.com>

- "alpha" is obsoleted in favor of "beta" in Persistant volume claim definition 

---

hawkular-metrics/Dockerfile

We need to update the ALPN version to better match the current version of OpenJDK.
Otherwise this will cause failures with https connections and prevent metrics from being deployed.

BZ1434902: update ALPN version for updated OpenJDK version

---

hawkular-metrics/hawkular-metrics-wrapper.sh

We've seen confusion around this message being printed for errors that have nothing to do with authorization. This prints specific messages for 401 and 403 errors, and just outputs the status code encountered for the rest

Clarify preflight message

---

hawkular-metrics/hawkular-metrics-wrapper.sh

An upcoming update for Hawkular Metrics will require monitoring the namespaces in the cluster. This adds a check if the current service account has this permission and instructions for how to add it required.

Add check for hawkular namespace listening

---

cassandra/cassandra.yaml.template

We have been using commit log compression, but other commit log
settings in cassandra.yaml assume compression is disabled. I think
this is why we have run into problems with running out of memory
during commit log replay.
Compression was turned on as an optimization. The safest course
at least for now is to simply revert back to out of the box
settings.

[BZ 1473013] disable commit log compression

---

cassandra/cassandra-docker.sh
hawkular-metrics/standalone.conf

Perform a case insensitive comparison of ENABLE_PROMETHEUS_ENDPOINT var to avoid any issues over ```true``` vs ```True```

[BZ 1508496] do case insensitive comparison

---

.gitignore
hack/build-images.sh
hawkular-metrics/Dockerfile
hawkular-metrics/dev/README.adoc

To date there has been no support for building images with locally built
versions of hawkular-metrics. The docker build only produces images that
include released versions of hawkular-metrics that get downloaded from
the JBoss nexus repo. This makes it awkward and error prone to test
changes that have not been released. I have resorted to modifying the
Dockerfile to copy a locally built hawkular-metrics EAR.
This commit adds support for building images with locally built versions
with a few small changes. The build-images.sh script has a --dev option
to indicate a dev build. If the dev flag is set and if a
hawkular-metrics.ear file exists in the hawkular-metrics/dev directory,
then it will be used. The hawkular-metrics version environment variable
will be ignored.

Add support for building dev images

---

heapster-base/BZ1474099.patch
heapster-base/Dockerfile

* Adds detection of stale cached definitions
* Reduces the amount of memory used for caching of each object (uses a hashcode instead of object)
* Speeds up initial startup time by fetching all definitions from Hawkular-Metrics in a single call
* Requires new version of Hawkular-Metrics

[BZ 1474099] Improve restart performance and reduce the memory usage

---

cassandra/Dockerfile
cassandra/cassandra-poststart.sh
cassandra/cassandra.yaml.template

Disabling auto snapshots for Cassandra by default because 1) we do not
have a mechanism for snapshots and because 2) the temp data temp tables
introduced in OpenShift 3.7 generate a lot of snapshots that can eat up
disk space in a hurry.
This commit introduces a new environment variable, TAKE_SNAPSHOT, which
if set to "true" will cause a snapshot to be generated in the
cassandra-poststart.sh script which is run from the postStart lifecycle
hook. The snapshop name uses a default value of a timestamp.

[BZ 1567251] Disable auto snapshots and env var for taking snapshots
